# Generated by Django 4.0.6 on 2022-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('article_type', models.CharField(choices=[('1', 'Top'), ('2', 'Bottoms'), ('3', 'Dress'), ('4', 'Jumpsuit/Romper'), ('5', 'Sweater'), ('6', 'Cardigan'), ('7', 'Outerwear'), ('8', 'Bodysuit'), ('9', 'Lingerie'), ('10', 'Shoes'), ('11', 'Accessory'), ('12', 'Socks/Tights')], default='1', max_length=2)),
                ('category', models.CharField(choices=[('1', 'Loungewear'), ('2', 'Casual'), ('3', 'Formal'), ('4', 'Party'), ('5', 'Work')], default='1', max_length=1)),
                ('brand', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
