# Generated by Django 4.0.6 on 2022-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
