# Generated by Django 4.0.6 on 2022-07-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0003_alter_article_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(choices=[('1', 'Red'), ('2', 'Orange'), ('3', 'Yellow'), ('4', 'Blue'), ('5', 'Green'), ('6', 'White'), ('7', 'Beige'), ('8', 'Cream'), ('9', 'Black'), ('10', 'Purple'), ('11', 'Pink'), ('12', 'Gray'), ('13', 'Brown'), ('14', 'Tan'), ('15', 'Multi')], default='1', max_length=2),
        ),
    ]
